version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    ports:
      - "3005:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: yarn start:dev
